CREATE TABLE cids (

    id BIGSERIAL PRIMARY KEY,

    code VARCHAR(10) NOT NULL UNIQUE,

    description TEXT NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);